apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: docker.io/bbachin1/angular-java-webapp
      name: webapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8080
